### PR TITLE
Fixed dev.office.com-related links in add-in MD note

### PR DESCRIPTION
**Pull request by Rapdash**
###### Skip this paragraph if you don't like fun
Hey MSFT Dudes, Dudettes, et al...
I was browsing at the Office Open XML (eXTREMELY MERCILESS LANGUAGE) docs, and while the documentation was like 95% tubular, I had a no-bueno run in with a pair of EVIL broken links... I trench-coated the new urls (dug the new ones up like a trench, then covered for whoever broke them like a coat of paint) and asked you guys for the dankest of pulls to GET THAT CODE IN THERE. Take a look and approve, and this docs page will be totally tubular once more.

### SUPER Serious PR Summary
---
It looks like dev.office.com is a (newly?) dead subdomain that got migrated into docs.microsoft.com. I updated a pair of broken urls to match the new locations for the originally intended resources. I'm 95% sure the amended urls match what the old resources were, but if I'm wrong, just know that the links are broken. Thanks for all the awesome stuff you make!
Cheers,
Rapdash

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[4eeeb8c](https://github.com/Rapdash/open-xml-docs/commits/4eeeb8c72ebc539d5986c62732ad729f624153c7)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e8f42630)

<a id="e8f42630"></a>
###
 - **Line 136**: **[Error]** `````Restore nuget package W:\yen1-s\.optemp\dependentPackages\Microsoft.OpenPublishing.CommonPlugins\packages.config in folder:W:\yen1-s\.optemp\packages failed, possibly due to transient errors from nuget servers. Please retry building your content. If the issue still happens, open a ticket in https://SiteHelp and include the build report and the following error message for our team to troubleshoot: Errors in packages.config projects     Unable to find version '1.0.222' of package 'Microsoft.OpenPublishing.CommonPlugins'.       C:\Users\ContainerAdministrator\.nuget\packages\: Package 'Microsoft.OpenPublishing.CommonPlugins.1.0.222' is not found on source 'C:\Users\ContainerAdministrator\.nuget\packages\'.       https://docfx.pkgs.visualstudio.com/docfx/_packaging/docs-build-v2-prod/nuget/v2: Package 'Microsoft.OpenPublishing.CommonPlugins.1.0.222' is not found on source 'https://docfx.pkgs.visualstudio.com/docfx/_packaging/docs-build-v2-prod/nuget/v2'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C5%5C4%5C8e850733-81e8-e221-a7da-a3951a35036c%5CPullRequest%5C202005042230087298-39%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TFfbLrqKDbZf0g9RUgXuDg%2FdvnL5Tee5Y39RIcXp1XE%3D&st=2020-05-04T22%3A25%3A47Z&se=2020-06-04T22%3A30%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Rapdash** [comment]
@lindalu-MSFT Hey, Linda. I don't know which branch this was supposed to be merged with, or what the build check error means, but I just shared this fix for a couple broken links in the markdown. Are you the person to ping about this?

**Comment by lindalu-MSFT** [comment]
@Rapdash Hi, thanks for bringing this to my attention! THis is an older repo that isn't monitored so I'm glad you pointed this out becasue all 5 open PRs have build errors. It looks like this is a job for the kind folks over at Docs Support. I'll get in touch and ask them what they think is causing this.

**Comment by Rapdash** [comment]
I'm going to close this & let people who know what they're doing handle it. Thanks!

**Pull request closed without merging**
